### ISSUE TITLE
eWallet_MobileApp(Register to TnG Application - Existing)_ IOS only #100

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#111]
[Defect_Mobile App #100.xlsx](https://github.com/TNGSB/eWallet/files/591406/Defect_Mobile.App.100.xlsx)

Test Description : To validate error message displayed when only "Name" field are left blank
Defect Description : System allowed IOS user to proceed to next page with "Name" fields in blank. No error message displayed.

Refer attachment for POT

**Comment by mayyeap** [comment]
send to fix, should be fixed end month build

**Comment by mayyeap** [comment]
![d63af898-aea6-486b-b3af-99105afbfd59](https://cloud.githubusercontent.com/assets/23113169/20453535/9ba09408-ae63-11e6-942b-b0ff5c73dd58.jpg)

**Comment by farahmohamad** [comment]
Hi May,

May I know you tested in which build?
I tested both build 38 (live) and build 34(dev) still the same.

Refer the attachment for POT.
![whatsapp image 2016-11-21 at 11 45 22 am 1](https://cloud.githubusercontent.com/assets/23113211/20470081/255a33fc-afe0-11e6-86b2-875ff26bfd4b.jpeg)
![whatsapp image 2016-11-21 at 11 45 22 am](https://cloud.githubusercontent.com/assets/23113211/20470082/299c9e96-afe0-11e6-9a81-ece3dfaf099c.jpeg)

Thanks!

**Comment by mayyeap** [comment]
new build which will release this few days. Please check on wednesday

**Comment by farahmohamad** [comment]
Hi May,

Retested with build 38 and 46 as per instruction.

Refer attached POT for your reference.

Thanks
[Defect_Mobile App #100-retest.xlsx](https://github.com/TNGSB/eWallet/files/618319/Defect_Mobile.App.100-retest.xlsx)
